# This is a basic workflow to help you get started with Actions

name: Update Image Tag

# Controls when the workflow will run
on:
  workflow_dispatch:
  repository_dispatch:
    types: update-image-tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        
      - name: Gather Image Information
        run: |
          echo IMAGE_NAME=${{ github.event.client_payload.imageName }}  >> $GITHUB_ENV
          echo IMAGE_TAG=${{ github.event.client_payload.imageTag }} >> $GITHUB_ENV
          echo SHA=${{ github.event.client_payload.sha }} >> $GITHUB_ENV
          echo REF=${{ github.event.client_payload.ref }} >> $GITHUB_ENV
          echo GITHUB_BASE_REF=${{ github.event.client_payload.github_base_ref }} >> $GITHUB_ENV
          echo COMMIT_MESSAGE=${{ github.event.client_payload.commitMessage }} >> $GITHUB_ENV
          echo LAST_COMMIT_BY=${{ github.event.client_payload.lastCommitBy }} >> $GITHUB_ENV
          echo EVENT_NAME=${{github.event.client_payload.event_name }} >> $GITHUB_ENV

      - name: Update QA values.yaml
        if:  ${{ contains(env.REF, 'develop') || contains(env.GITHUB_BASE_REF, 'develop') }}
        id: update_qa_image_tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(. | .deploymentList["${{env.IMAGE_NAME}}"].imageTag="${{env.IMAGE_TAG}}")' helm-values/qa/values.yaml
          
      - name: Update Release values.yaml
        if:  ${{ contains(env.REF, 'release') || contains(env.GITHUB_BASE_REF, 'release') }}
        id: update_release_image_tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(. | .deploymentList["${{env.IMAGE_NAME}}"].imageTag="${{env.IMAGE_TAG}}")' helm-values/release/values.yaml

      # # tmate session for debugging
      # - name: Setup tmate session for debugging
      #   uses: mxschmitt/action-tmate@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Update ${{env.IMAGE_NAME}} with image tag ${{env.IMAGE_TAG}}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: pr-${{ github.run_number }}
          delete-branch: true
          title: "update-${{env.IMAGE_NAME}}-with-tag-${{env.IMAGE_TAG}}"
          body: |
            :sunny::sunny::sunny: UPDATE IMAGE :sunny::sunny::sunny:
            - :v: New service image built with tag ${{env.IMAGE_TAG}} on branch ${{env.REF}}
            - :ticket: Event Name: ${{env.EVENT_NAME}}
            - :whale2: Image Name: ${{env.IMAGE_NAME}}
            - :candy: Image Tag: ${{env.IMAGE_TAG}}
            - :green_apple: Branch: ${{env.REF}}
            - :apple: Base Branch: ${{env.GITHUB_BASE_REF}}
            - :octocat: Last Commit By: ${{env.LAST_COMMIT_BY}}
            - :incoming_envelope: Commit Message: ${{env.COMMIT_MESSAGE}}
            - :pencil2: Commit Hash: ${{env.SHA}}
            - :rocket: Merge the PR to deploy ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
            - Auto-generated by [create-pull-request][1]
          labels: |
            automated pr
          assignees: scvolea/lls-dev-leads
          reviewers: scvolea/olea-dev-leads
          # team-reviewers: |
          #   developers
          #   qa-team
          # milestone: 1
          # draft: false
